type: "evaluation"
input_dir: "task_outputs/sft-regression"
dataset_dir: "task_outputs/ecare"
output_dir: "task_outputs/evaluation-ecare-sft"
dependencies:
  # training: "configs/training/sft_regression.yaml"
  dataset: "configs/dataset/ecare.yaml"