type: "evaluation"
input_dir: "task_outputs/sft-regression-mse-reg"
dataset_dir: "task_outputs/unli-dataset-preparation-completion"
output_dir: "task_outputs/evaluation-mse-reg"
dependencies:
  training: "configs/training/sft_regression_with_mse.yaml"
  dataset: "configs/dataset/unli-dataset-preparation-completion.yaml"