type: "evaluation"
input_dir: "task_outputs/sft-regression"
dataset_dir: "task_outputs/unli-dataset-preparation-completion"
output_dir: "task_outputs/evaluation"
dependencies:
  # training: "configs/training/sft_regression.yaml"
  dataset: "configs/dataset/unli-dataset-preparation-completion.yaml"