type: "dataset-preparation"
output_dir: "task_outputs/entailmentbank"
dataset_processor:
  datapath: "data/synthetic/EntailmentBank_test.jsonl"
  type: "multi-premise"
  number_of_levels: 10
  template:
    type: "unli"